theme = "tokyonight_storm"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
W = ["extend_next_word_start"]
X = ["extend_line_up"]
e = ["extend_to_line_end"]
E = ["extend_to_line_start"]

[editor.cursor-shape]
insert = "bar"
