theme = "tokyonight_storm"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
W = ["extend_next_word_start"]
X = ["select_line_above"]
e = ["extend_to_line_end"]
E = ["extend_to_line_start"]

[editor]
bufferline = "multiple"
true_color = true  

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true
